friends=["Rolf","Bob","Jen","Anne",1,2,4,310]
print(friends)
friends[3]="jennie"
print(friends)
print(friends[2:5])
friends.append("Smith")
print(friends)      
friends.insert(1,"Kelly")
print(friends)
friends.remove("Bob")
print(friends)